TRAINING_FEATURES = [
    # LOW
    {
        "alert_count": 1,
        "high_severity_alerts": 0,
        "critical_severity_alerts": 0,
        "error_alerts": 0,
        "timeout_alerts": 0,
        "connection_alerts": 0,
        "resource_alerts": 1,
        "log_count": 0,
        "dependency_count": 0,
        "recent_change_count": 0,
        "has_metrics": 1,
        "has_system_state": 1,
    },
    {
        "alert_count": 2,
        "high_severity_alerts": 0,
        "critical_severity_alerts": 0,
        "error_alerts": 1,
        "timeout_alerts": 0,
        "connection_alerts": 0,
        "resource_alerts": 1,
        "log_count": 1,
        "dependency_count": 0,
        "recent_change_count": 0,
        "has_metrics": 1,
        "has_system_state": 1,
    },

    # MEDIUM
    {
        "alert_count": 2,
        "high_severity_alerts": 1,
        "critical_severity_alerts": 0,
        "error_alerts": 1,
        "timeout_alerts": 1,
        "connection_alerts": 0,
        "resource_alerts": 0,
        "log_count": 1,
        "dependency_count": 1,
        "recent_change_count": 0,
        "has_metrics": 1,
        "has_system_state": 1,
    },
    {
        "alert_count": 3,
        "high_severity_alerts": 1,
        "critical_severity_alerts": 0,
        "error_alerts": 2,
        "timeout_alerts": 1,
        "connection_alerts": 1,
        "resource_alerts": 0,
        "log_count": 2,
        "dependency_count": 1,
        "recent_change_count": 0,
        "has_metrics": 1,
        "has_system_state": 1,
    },
    {
        "alert_count": 4,
        "high_severity_alerts": 1,
        "critical_severity_alerts": 0,
        "error_alerts": 2,
        "timeout_alerts": 0,
        "connection_alerts": 1,
        "resource_alerts": 0,
        "log_count": 2,
        "dependency_count": 2,
        "recent_change_count": 0,
        "has_metrics": 1,
        "has_system_state": 1,
    },

    # HIGH
    {
        "alert_count": 4,
        "high_severity_alerts": 2,
        "critical_severity_alerts": 0,
        "error_alerts": 2,
        "timeout_alerts": 1,
        "connection_alerts": 1,
        "resource_alerts": 0,
        "log_count": 3,
        "dependency_count": 2,
        "recent_change_count": 1,
        "has_metrics": 1,
        "has_system_state": 1,
    },
    {
        "alert_count": 5,
        "high_severity_alerts": 2,
        "critical_severity_alerts": 0,
        "error_alerts": 3,
        "timeout_alerts": 1,
        "connection_alerts": 1,
        "resource_alerts": 0,
        "log_count": 4,
        "dependency_count": 2,
        "recent_change_count": 1,
        "has_metrics": 1,
        "has_system_state": 1,
    },
    {
        "alert_count": 6,
        "high_severity_alerts": 2,
        "critical_severity_alerts": 1,
        "error_alerts": 3,
        "timeout_alerts": 2,
        "connection_alerts": 1,
        "resource_alerts": 0,
        "log_count": 5,
        "dependency_count": 3,
        "recent_change_count": 1,
        "has_metrics": 1,
        "has_system_state": 1,
    },
    {
        "alert_count": 5,
        "high_severity_alerts": 3,
        "critical_severity_alerts": 0,
        "error_alerts": 3,
        "timeout_alerts": 1,
        "connection_alerts": 2,
        "resource_alerts": 0,
        "log_count": 4,
        "dependency_count": 3,
        "recent_change_count": 2,
        "has_metrics": 1,
        "has_system_state": 1,
    },

    # CRITICAL
    {
        "alert_count": 7,
        "high_severity_alerts": 3,
        "critical_severity_alerts": 2,
        "error_alerts": 4,
        "timeout_alerts": 2,
        "connection_alerts": 2,
        "resource_alerts": 0,
        "log_count": 7,
        "dependency_count": 3,
        "recent_change_count": 2,
        "has_metrics": 1,
        "has_system_state": 1,
    },
    {
        "alert_count": 9,
        "high_severity_alerts": 3,
        "critical_severity_alerts": 3,
        "error_alerts": 5,
        "timeout_alerts": 2,
        "connection_alerts": 2,
        "resource_alerts": 0,
        "log_count": 9,
        "dependency_count": 4,
        "recent_change_count": 2,
        "has_metrics": 1,
        "has_system_state": 1,
    },
    {
        "alert_count": 10,
        "high_severity_alerts": 4,
        "critical_severity_alerts": 3,
        "error_alerts": 5,
        "timeout_alerts": 3,
        "connection_alerts": 2,
        "resource_alerts": 0,
        "log_count": 10,
        "dependency_count": 4,
        "recent_change_count": 3,
        "has_metrics": 1,
        "has_system_state": 1,
    },
]


TRAINING_LABELS = [
    "low",
    "low",
    "medium",
    "medium",
    "medium",
    "high",
    "high",
    "high",
    "high",
    "critical",
    "critical",
    "critical",
]